### ISSUE TITLE
prettyMdPdf.convertMd

### ISSUE THREAD

**Issue by gamgamstylep** [djfdyuruiry/pretty-markdown-pdf#16]
prettyMdPdf.convertMdToPdf({ markdownFilePath: "my-doc.md" })

should be

prettyMdPdf.convertMd({ markdownFilePath: "my-doc.md" })

This is also valid for the other occurrences in the ReadMe.md File.

**Comment by djfdyuruiry** [comment]
This has been corrected in v1.5.0
