### ISSUE TITLE
config file: highlightStyle file doesnt work

### ISSUE THREAD

**Issue by gamgamstylep** [djfdyuruiry/pretty-markdown-pdf#17]
Own highlight style will not be replaced but appended:

"highlightStyle": "c:\\configFile.json",

output:
ENOENT: no such file or directory, access
'C:\Users\username\AppData\Roaming\npm\node_modules\pretty-markdown-pdf\node_modules\highlight.js\styles\c:\configFile.json'

**Comment by djfdyuruiry** [comment]
This is now fixed in v1.5.0

**Comment by djfdyuruiry** [comment]
See the README changes for `highlightStyle` config option
