### ISSUE TITLE
auto-size to content

### ISSUE THREAD

**Issue by apobekiaris** [djfdyuruiry/pretty-markdown-pdf#8]
Hi I used the package to create tweeted images like

https://pbs.twimg.com/media/EWmK_mQX0AAwXpg?format=jpg&name=medium
![image](https://user-images.githubusercontent.com/159464/80351167-88290a00-887a-11ea-9915-f64f154c5243.png)

I guess it have apply some styling to it but not sure what. Can you please direct me how to auto-size to content?

**Comment by djfdyuruiry** [comment]
Hi! I am not actively developing this package at the moment but open to PRs
