### ISSUE TITLE
Improve the compatibility on Plant UML inclusion

### ISSUE THREAD

**Issue by dlastov** [djfdyuruiry/pretty-markdown-pdf#9]
For the daily work I use IntelliJ with its [Markdown plugin](https://www.jetbrains.com/help/idea/markdown.html).

In order to display plant uml diagrams using that, following syntax is suggested (please ignore the extra spaces between ` characters):
```
` ` `puml
Bob -[#red]> Alice : hello
Alice -[#0000FF]->Bob : ok
` ` `
```

this also works
```
` ` `puml
@startuml
Bob -[#red]> Alice : hello
Alice -[#0000FF]->Bob : ok
@enduml
` ` `
```
However, none of the above works with pretty-markdown-pdf. I need to use the below, which is not supported by the IntelliJ environment:
```
@startuml
Bob -[#red]> Alice : hello
Alice -[#0000FF]->Bob : ok
@enduml
```
It seems to me that the IntelliJ's syntax is closer to Markdown specification. Can it be supported by pretty-markdown-pdf?

This [Visual Studio plugin](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml) suggests the syntax below, also supported by IntelliJ, maybe that would be the most compatible:

```
` ` `plantuml
@startuml
Bob -[#red]> Alice : hello
Alice -[#0000FF]->Bob : ok
@enduml
` ` `
```

**Comment by djfdyuruiry** [comment]
Hi @dlastov 

I am not actively developing this package at the moment, but happy to take PRs.
